apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: sa-gcs-access
    sklearn:
      storageUri: gs://churn-model-bucket-manoj/models/churn_model.pkl
