apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: churn-predictor
  namespace: churn-model
spec:
  predictor:
    serviceAccountName: sa-gcs-access
    sklearn:
      storageUri: gs://churn-model-bucket-manoj/models/churn_model.pkl
      resources:
        requests:
          cpu: "10m"      # Reduced from 1 CPU (1000m) to 0.1 CPU
          memory: "256Mi"  # Reduced from 2Gi to 256MB
        limits:
          cpu: "500m"
          memory: "1Gi"