apiVersion: v1
kind: Namespace
metadata:
  name: churn-model
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: gcs-secret
#  namespace: churn-model
#type: Opaque
#stringData:
#  gcloud-application-credentials.json: |
#    {
#      "type": "service_account",
#      "project_id": "project-722e0926-2abc-479e-97f",
#      "private_key_id": "...",
#      "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
#      "client_email": "github-actions-sa@project-722e0926-2abc-479e-97f.iam.gserviceaccount.com",
#      "client_id": "...",
#      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#      "token_uri": "https://oauth2.googleapis.com/token",
#      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#      "client_x509_cert_url": "..."
#    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-gcs-access
  namespace: churn-model
  annotations:
    # Binds directly to GCP IAM via Workload Identity (No JSON keys required!)
    iam.gke.io/gcp-service-account: "github-actions-sa@project-722e0926-2abc-479e-97f.iam.gserviceaccount.com"
