name: MLOps Pipeline

on:
  push:
    branches: ["*"]
  workflow_dispatch:

env:
  GCP_REGION: asia-south1
  GCS_BUCKET: churn-model-bucket-manoj

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push commits
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Generate dataset
      run: python generate_data.py
    
    - name: Train model
      run: python train.py
    
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/165993017700/locations/global/workloadIdentityPools/github-pool/providers/github-provider' # 👈 Replace with your string
        service_account: 'github-actions-sa@project-722e0926-2abc-479e-97f.iam.gserviceaccount.com' # 👈 Replace with your SA email

    # Setting up the gcloud CLI tool automatically uses the credentials generated above
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Push model to GCS directly
      run: |
        gsutil cp models/churn_model.pkl gs://churn-model-bucket-manoj/models/churn_model.pkl
        echo "Model pushed to GCS is success"
    
    - name: Update inference.yaml with GCS model path
      run: |
        MODEL_URI="gs://churn-model-bucket-manoj/models/churn_model.pkl"
        sed -i "s|storageUri: .*|storageUri: $MODEL_URI|g" k8s/inference.yaml
    
    - name: Commit updated inference.yaml
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/inference.yaml
        git commit -m "Update model GCS path [skip ci]" || echo "No changes"
        git push || echo "No changes to push"
